### ISSUE TITLE
Reflection mode is possible?

### ISSUE THREAD

**Issue by ravipurohit1991** [FABLE-3DXRD/xrd_simulator#1]
Hello, 
Thank you for this nice library. I had a question, I haven't explored deeply the code yet and was wondering does the code also simulates reflection geometry or is it transmission alone?
Thanks,
Cheers,
Ravi.

**Comment by AxelHenningsson** [comment]
Hi! Thanks. 😃 

I am unsure to what you mean by reflection vs transmission. The code simulates diffraction as collected by a 2D area detector assuming crystals that obey Braggs law under the illumination of xrays. Could you please elaborate. 🙂 

Best,
Axel

**Comment by AxelHenningsson** [comment]
Hi again, I will close this thread if you do not have any follow up questions.

Kind Regards
Axel Henningsson
