### ISSUE TITLE
Installation Dependency/ies (HDF5) not resolved - Installation from source

### ISSUE THREAD

**Issue by vamatya** [FABLE-3DXRD/xrd_simulator#12]
Platform: Mac M2
OS: MacOS (Ventura)
Python Version: 10
Installation command: python setup.py install (from source)
Git Commit: 75d31b3ef5ae31c3a6d86cae68631baf542326ca (HEAD -> main

Error: 
...
Package hdf5 was not found in the pkg-config search path.
Perhaps you should add the directory containing `hdf5.pc'
to the PKG_CONFIG_PATH environment variable
No package 'hdf5' found
    HDF5_DIR environment variable not set, checking some standard locations ..
...
File "/var/folders/_1/nr4c208j18nb42tlk8sc66j00000gn/T/easy_install-cy3ya1ie/netcdf4-1.7.1.post1/setup.py", line 277, in <module>
File "/var/folders/_1/nr4c208j18nb42tlk8sc66j00000gn/T/easy_install-cy3ya1ie/netcdf4-1.7.1.post1/setup.py", line 226, in _populate_hdf5_info
ValueError: did not find HDF5 headers

Should there already be HDF5 installed? Can h5py be of any part of the solution?

**Comment by AxelHenningsson** [comment]
Thanks a lot for posting issues on this repo. This helps us a lot to get better! 👏 😄 

 To the point, I would guess

```brew install hdf5```

does the trick. This is not an issue with ```xrd_simulator``` but is simply a feature of h5py - it just requires certain binaries to run. My guess is that you will get the same error from running

```pip3 install h5py ```

Going with Anaconda would also solve this: ```conda install anaconda::h5py ```.

[See also the docs](https://docs.h5py.org/en/stable/build.html)

Cheers 🥂 
Axel
