### ISSUE TITLE
Issue while generating polycrystal with strain value at different strain tensor location

### ISSUE THREAD

**Issue by vamatya** [FABLE-3DXRD/xrd_simulator#17]
Hi, 

I'm trying to understand how the software generates strain onto the polycrystal. For this I'm using the follwing example:  [s3dxrd_odf_sample.py](https://github.com/FABLE-3DXRD/xrd_simulator/blob/main/tests/end_to_end_tests/s3dxrd_odf_sample.py). In the file, strain tensor is defined as follows: 

`def strain_tensor(x): return np.array(
    [[0, 0, 0], [0, 0, 0], [0, 0, 0.02 * x[2] / sample_bounding_cylinder_height]])`, which works. Now if I try to change this to the following: 

`def strain_tensor(x): return np.array(
    [[0, 0, 0], [0, 0.02 * x[1]/ 2*sample_bounding_cylinder_radius, 0], [0, 0, 0]])`, I get the following error: 

================

{
	"name": "ValueError",
	"message": "Unfeasible strain tensor with value: [array([-0.82774914,  2.5397373 ,  8.55612262]), array([  2.5397373 ,  -7.79253667, -26.25228181]), array([  8.55612262, -26.25228181, -88.44132918]), array([-59.01748957, -27.48214177, -64.73926445]), array([-139.02660485,  -64.73926445, -152.50530313]), array([  42.29164645,  -37.70126348, -325.63410577])], will invert the unit cell with negative deformation gradient tensor determinant",
	"stack": "---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File XRD/xrd_simulator/tests/end_to_end_tests/s3dxrd_odf_sample_austenite_strain.py:114
    112 print(phase_fraction)
    113 # print(phase_fraction[0], phase_fraction[1])
--> 114 polycrystal = templates.polycrystal_from_odf(orientation_density_function,
    115                                             number_of_crystals,
    116                                             sample_bounding_cylinder_height,
    117                                             sample_bounding_cylinder_radius,
    118                                             unit_cell,
    119                                             sgname,
    120                                             path_to_cif_file,
    121                                             maximum_sampling_bin_seperation,
    122                                             strain_tensor,
    123                                             phase_fraction)
    124 path = os.path.join(
    125     os.path.join(
    126         os.path.dirname(__file__),
    127         'saves'),
    128     # 'polycrystal_from_odf.pc')
    129     'Austenite_gs_100000_from_odf_cif_pf_strain_8pc_yy.pc')
    130     # 'Austenite_gs_100000_from_odf_cif_pf_strain_8pc_zz.pc')
    131     # 'Austenite_gs_100000_from_odf_cif_pf_strain_test1_no_strain.pc')

File miniconda3/envs/xrd_sim_py3.10/lib/python3.10/site-packages/xrd_simulator-0.4.1-py3.10.egg/xrd_simulator/templates.py:216, in polycrystal_from_odf(orientation_density_function, number_of_crystals, sample_bounding_cylinder_height, sample_bounding_cylinder_radius, unit_cell, sgname, path_to_cif_file, maximum_sampling_bin_seperation, strain_tensor, phase_fractions)
    212 for ei in range(mesh.number_of_elements):
    213     # strain in lab/sample-coordinates
    214     strain_lab[ei] = strain_tensor(mesh.ecentroids[ei])
--> 216 return Polycrystal(
    217     mesh,
    218     orientation,
    219     strain=strain_lab,
    220     phases=phases,
    221     element_phase_map=element_phase_map,
    222 )

File miniconda3/envs/xrd_sim_py3.10/lib/python3.10/site-packages/xrd_simulator-0.4.1-py3.10.egg/xrd_simulator/polycrystal.py:282, in Polycrystal.__init__(self, mesh, orientation, strain, phases, element_phase_map)
    278 self.strain_lab = self._instantiate_strain(strain, mesh)
    279 self.element_phase_map, self.phases = self._instantiate_phase(
    280     phases, element_phase_map, mesh
    281 )
--> 282 self._eB = self._instantiate_eB(
    283     self.orientation_lab,
    284     self.strain_lab,
    285     self.phases,
    286     self.element_phase_map,
    287     mesh,
    288 )
    290 # Assuming sample and lab frames to be aligned at instantiation.
    291 self.mesh_lab = copy.deepcopy(mesh)

File miniconda3/envs/xrd_sim_py3.10/lib/python3.10/site-packages/xrd_simulator-0.4.1-py3.10.egg/xrd_simulator/polycrystal.py:562, in Polycrystal._instantiate_eB(self, orientation_lab, strain_lab, phases, element_phase_map, mesh)
    560     B0s[i] = tools.form_b_mat(phase.unit_cell)
    561     grain_indices = np.where(np.array(element_phase_map) == i)[0]
--> 562     _eB[grain_indices] = utils.lab_strain_to_B_matrix(
    563         strain_lab[grain_indices], orientation_lab[grain_indices], B0s[i]
    564     )
    566 return _eB

File miniconda3/envs/xrd_sim_py3.10/lib/python3.10/site-packages/xrd_simulator-0.4.1-py3.10.egg/xrd_simulator/utils.py:208, in lab_strain_to_B_matrix(strain_tensor, crystal_orientation, B0)
    202     crystal_orientation = crystal_orientation[np.newaxis, :, :]
    204 crystal_strain = np.matmul(
    205     crystal_orientation.transpose(0, 2, 1),
    206     np.matmul(strain_tensor, crystal_orientation),
    207 )
--> 208 B = _epsilon_to_b(crystal_strain, B0)
    209 return np.squeeze(B)

File miniconda3/envs/xrd_sim_py3.10/lib/python3.10/site-packages/xrd_simulator-0.4.1-py3.10.egg/xrd_simulator/utils.py:320, in _epsilon_to_b(crystal_strain, B0)
    318 eigen_vals = np.linalg.eigvalsh(C)
    319 if np.any(np.array(eigen_vals) < 0):
--> 320     raise ValueError(
    321         \"Unfeasible strain tensor with value: \"
    322         + str(_strain_as_vector(crystal_strain))
    323         + \", will invert the unit cell with negative deformation gradient tensor determinant\"
    324     )
    325 if C.ndim == 3:
    326     F = np.linalg.cholesky(C).transpose(0, 2, 1)

ValueError: Unfeasible strain tensor with value: [array([-0.82774914,  2.5397373 ,  8.55612262]), array([  2.5397373 ,  -7.79253667, -26.25228181]), array([  8.55612262, -26.25228181, -88.44132918]), array([-59.01748957, -27.48214177, -64.73926445]), array([-139.02660485,  -64.73926445, -152.50530313]), array([  42.29164645,  -37.70126348, -325.63410577])], will invert the unit cell with negative deformation gradient tensor determinant"
}

===========

The above examples uses a cylindrical sample volume. For the same, what would be an example of strain tensor values at XX or YY that'd work?

Thanks!

**Comment by AxelHenningsson** [comment]
Hi vamatya!

You cannot input arbitrarily large strains to the simulation, at some point the unit cell of the lattice will invert.

My best guess is that you forgot a paranthesis in the division in your strain function and that you are unintentionally creating very large strains? Compare 
```python
def strain_tensor(x): 
    return np.array( [[0, 0, 0], [0, 0.02 * x[1]/ 2*sample_bounding_cylinder_radius, 0], [0, 0, 0]])
```
to 
```python
def strain_tensor(x): 
    return np.array( [[0, 0, 0], [0, 0.02 * x[1]/ (2*sample_bounding_cylinder_radius), 0], [0, 0, 0]])
```
the later works well for me:
![image](https://github.com/user-attachments/assets/7a1be8d5-541d-4f1f-8998-ed73dbc28408)

Note that in python `x[1]/ 2*sample_bounding_cylinder_radius=sample_bounding_cylinder_radius*(x[1]/ 2)` so probably not what you want ;)

**Comment by vamatya** [comment]
Doh...! I learned something today. Thanks! :)
